### PR TITLE
[Terms of service] remove 'Terms of service' from the footer (Issue #60)

### PR DESCRIPTION
**Pull request by bugITwhisperer**
## Changes proposed
- remove 'Terms of service' from footer as per Rahul's confirmation here: https://github.com/Git21221/IBMSkillsBuild/issues/60#issuecomment-1751648180

### CODE REVIEW

**Comment by Git21221** [comment]
@bugITwhisperer can you send a screenshot of new footer?

**Comment by bugITwhisperer** [comment]
@Git21221 : sure thig! Here is a screenshot of footer w/out the 'Terms of service':
2023-10-09_10h04_22

**Comment by Git21221** [comment]
@bugITwhisperer ok that's great.

**Review by Git21221 — APPROVED** [review]
Deleted all terms of service from all pages.

**Pull request merged**
